In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings; warnings.filterwarnings('ignore')

url = 'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv'
df = pd.read_csv(url)
# print(df.head())
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce').fillna(0)
print('Loaded:', df.shape)

Loaded: (7043, 21)

In [13]:
cat_cols = df.select_dtypes(include='object').columns.tolist()
print('Categorical columns:', cat_cols)
print('Total:', len(cat_cols))

Categorical columns: ['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']
Total: 17

In [14]:
df['Contract'].value_counts()

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [15]:
dummies = pd.get_dummies(df['Contract'], prefix='Contract')
print('Shape before:', df[['Contract']].shape, '-> after:', dummies.shape)
dummies.head()

Shape before: (7043, 1) -> after: (7043, 3)

   Contract_Month-to-month  Contract_One year  Contract_Two year
0                     True              False              False
1                    False               True              False
2                     True              False              False
3                    False               True              False
4                     True              False              False

In [16]:
dummies2 = pd.get_dummies(df['Contract'], prefix='Contract', drop_first=True)
print('With drop_first:', dummies2.shape)
dummies2.head()

With drop_first: (7043, 2)

   Contract_One year  Contract_Two year
0              False              False
1               True              False
2              False              False
3               True              False
4              False              False

In [17]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
encoded = ohe.fit_transform(df[['PaymentMethod']])
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(['PaymentMethod']))
encoded_df.head()

,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0

In [18]:
df['Churn_bin'] = df['Churn'].map({'No': 0, 'Yes': 1})
df[['Churn', 'Churn_bin']].head()

  Churn  Churn_bin
0    No          0
1    No          0
2   Yes          1
3    No          0
4   Yes          1

In [19]:
multi = pd.get_dummies(df[['gender', 'Contract', 'PaymentMethod']], drop_first=True)
print('Shape:', multi.shape)
multi.head()

Shape: (7043, 6)

,gender_Male,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,False,False,False,False,True,False
1,True,True,False,False,False,True
2,True,False,False,False,False,True
3,True,True,False,False,False,False
4,False,False,False,False,True,False