# Module 2 — Class 4: Pandas for Data Analysis

**Lecture:** [https://bepro-aiml.github.io/aiml-platform/#/module/2/class/4](https://bepro-aiml.github.io/aiml-platform/#/module/2/class/4)

## How to use this notebook

Every section has the same shape:
1. **Concept** — short explanation from the lecture.
2. **Predict** — write what you think will happen *before* running the code.
3. **Run** — execute the cell.
4. **Explain** — write 1–2 sentences in your own words about what the code did and why.
5. **Practice** — your turn. The grade is on the markdown cells, not just running the code.

Skipping the markdown cells = automatic 0 on the in-class checkpoint. Run code without thinking and you will be lost by Class 5.

---
## 1. Series and DataFrames

**Concept.** Pandas is a programmable spreadsheet. `Series` = one labeled column. `DataFrame` = 2D labeled table with an index. 90% of ML work starts with loading, cleaning, and engineering features in a DataFrame.

### 🤔 Predict

Before running the next two cells, answer in this cell:
1. What do you expect the output of `df` to look like? Sketch it in markdown (use a table).
2. What is the *index* of `df` going to be — and what does that even mean?

**Your prediction:**

In [1]:
# here we will creat 3 by 3 table, but I think virtually visualisation is
# converted 90 degrees. name, age, city (which i think are category type of
# things) are raw heads. and in each column there will be info about three people named
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Zara", "Jasur"],
    "age":  [22, 28, 31],
    "city": ["Tashkent", "Samarkand", "Bukhara"]
})
df

# for some reason my guess was not right as name, age and city are clearly on columns

    name  age       city
0    Ali   22   Tashkent
1   Zara   28  Samarkand
2  Jasur   31    Bukhara

In [2]:
# we will be printing the types here. first one should print number as all the
# input for age were numbers (integers to be specific). for the second one, i
# think it will print string and number. for the third, df is table which has
# indexes, one for raws, one for columns.

print(type(df['age']))
print(type(df[['name', 'age']]))
print(df.index)

# the results were similar, with one minor mistake. I think, because df is
# dataframe, when we are printing its type, instead of number or string (which
# are datatype) it printed series, which is right. The same thing for the second
# one. it prints type of two series, which is datafrome.

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)

### ✍️ Explain

Answer all three in your own words (one sentence each):
1. Why is `df['age']` a Series but `df[['name', 'age']]` a DataFrame?
2. What is the default index when you don't set one?
3. When would you *want* a non-default index? Give one realistic example.

**Your answer:**

1. age is only one column of data, and if data is set only on one direction it
is considered series.
2. the starting is always 0 and in default, if the step is not specified, it will be taken as 1. or we can just call them with their own category or individual indexes
3. example: we have data from each city of the uzbekistan, but we need only Andijan's data.
we use indexes to filter only neseccary data.

### 🛠 Practice

Build a DataFrame with at least 5 rows and 4 columns about something you actually care about (your music playlist, your subjects this semester, anything). Then:
- Set one of the columns as the index using `df.set_index('col_name')`.
- Show what `df.loc[<one of your index labels>]` returns.
- In a markdown cell, explain *why* `df.loc` finds that row even though it's not row 0.

In [16]:
# Your DataFrame here
my_df = pd.DataFrame({
    'col_name' : [10, 20, 30, 40, 50],
    'name' : ['Ali', 'Zara', 'Jasur', 'Madina', 'Otabek'],
    'age' : [22, 28, 31, 56, 98],
    'city' : ['Tashkent', 'Samarkand', 'Bukhara', 'Tashkent', 'Samarkand']

})
my_df = my_df.set_index('age')

my_df

my_df.loc[22]

col_name          10
name             Ali
city        Tashkent
Name: 22, dtype: object

because I set age as index, it will look for the value as set in the indexes. This is why when I entered 22, it looked through ages, and gave me the series whith 22 index

---
## 2. Loading and Exploring

**Concept.** Five inspection commands you will run on every dataset for the rest of your career: `head`, `shape`, `info`, `describe`, `isna().sum()`. Each one answers a different question.

### 🤔 Predict

For each of the five commands below, write **one sentence** about what *question* it answers — before running anything.

1. `df.head()` answers: it gives the number of raws we enter into bracets
2. `df.shape` answers: this should give us how many raws and columns are there in the dataframe
3. `df.info()` answers: this should give data about datatype if I am not mistaken.
4. `df.describe()` answers: I have no idea
5. `df.isna().sum()` answers: this will give how many nan values are there in the dataframe

In [ ]:
# Load any small CSV. If you don't have one, use this built-in dataset:
# from sklearn.datasets import load_iris
# iris = load_iris(as_frame=True)
# df = iris.frame

# Then run all 5 inspection commands. Don't combine them in one cell —
# put each in its own cell so you can read each output carefully.

In [17]:
from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)
df = iris.frame

df.head(5)
# worked the same way I guessed

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [18]:
df.shape
# worked the same way I guessed it would

(150, 5)

In [19]:
df.info()

# this showed more info about raws and columns with index too

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [23]:
df.isna().sum()
# works the same way i guessed, with also giving the datatype in the end. and it
# didn't just show total Nan values, but Nan values in each raw

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [20]:
df.describe()

# so this shows some calculated data about mean, standart daviation, minimum, maximum, and quirtiles

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

### ✍️ Explain

Compare your predictions above to what each command actually printed. For any prediction that was wrong, write what surprised you.

### 🛠 Practice

If your CSV has a column that *looks* like a date but `df.dtypes` shows it as `object`:
- Re-load with `pd.read_csv('...', parse_dates=['that_column'])`.
- Run `df.dtypes` again.
- In a markdown cell, explain why this matters. (Hint: try sorting by date when it's a string vs when it's a datetime.)

this matters because when it is in string form, when we compare date (for exampele day or month) it compares them in alphabetic order, not in a right date order. Example: December comes after November in calendar, even though D comes first in alphabet

---
## 3. Filtering, GroupBy, Merging

These are the three operations every data role uses every day. Master them and the rest of Pandas falls into place.

### 3a. Selection — `loc` vs `iloc`

**Concept.** `loc` selects by **label**. `iloc` selects by **integer position**. They behave the same only when your index happens to be `0, 1, 2, …` — once you set a meaningful index, they diverge.

### 🤔 Predict

Given the `df` from Section 1 (Ali, Zara, Jasur):
- What does `df.loc[0]` return? - gives a raw that belongs to Ali (at 0 index for now)
- What does `df.iloc[0]` return? - gives the same value
- Now imagine I run `df = df.set_index('name')`. After that:
  - What does `df.loc['Ali']` return? - gives the same thing, but before giving it set its index system to 'name', so it selects accordingly
  - What does `df.iloc[0]` return? - gives the same value because we are using iloc, which counts down without reading its values, but rather orders
  - What does `df.loc[0]` return?  *(careful — think before answering)* - this gives error, as we already set index as name, and there is not name '0'

In [26]:
df = pd.DataFrame({
    "name": ["Ali", "Zara", "Jasur"],
    "age":  [22, 28, 31],
    "city": ["Tashkent", "Samarkand", "Bukhara"]
})

print('--- before set_index ---')
print(df.loc[0])
print(df.iloc[0])

df = df.set_index('name')
print('--- after set_index ---')
print(df.loc['Ali'])
print(df.iloc[0])
# Try uncommenting the next line and explain the error in markdown below:
print(df.loc[0])
# there is no name that is 0, instead we can enter some existing name or use
# iloc [] - print(df.loc['Jasur'])


# in addition o giving the values of the indicadted index, it is also giving
# what index it is using and its datatype too

--- before set_index ---
name         Ali
age           22
city    Tashkent
Name: 0, dtype: object
name         Ali
age           22
city    Tashkent
Name: 0, dtype: object
--- after set_index ---
age           22
city    Tashkent
Name: Ali, dtype: object
age           22
city    Tashkent
Name: Ali, dtype: object
age          31
city    Bukhara
Name: Jasur, dtype: object

### ✍️ Explain

1. Which of your predictions were wrong? Why?
2. The commented `df.loc[0]` would raise an error. What error, and why does it make sense?
3. *Quick Check from the lecture:* In one sentence — when do you reach for `loc` and when for `iloc`?

### 3b. Boolean Filtering

### 🤔 Predict

Three of these four lines are wrong. Without running them, decide which one is correct and explain *why* the others fail.

```python
# A
df[df.age >= 18 and df.city == 'Tashkent']
# B
df[(df.age >= 18) & (df.city == 'Tashkent')]
# C
df[df.age >= 18 && df.city == 'Tashkent']

<!-- other three above won't work mainly because they are not manipulating data, but rather just reading them -->
# D
df.filter(age=18, city='Tashkent')
<!-- this works because it is manipulating and rewriting the data filtering throught it -->
```

**Correct one:** D
**Why each wrong one fails: the just read and cannot create or change any values without further functions

In [62]:
# Reload df without the index modification from earlier
df = pd.DataFrame({
    "name": ["Ali", "Zara", "Jasur", "Madina", "Otabek"],
    "age":  [22, 28, 31, 17, 45],
    "city": ["Tashkent", "Samarkand", "Bukhara", "Tashkent", "Samarkand"]
})

# Test the four candidates one at a time. Comment out 3, uncomment 1, run, repeat.

# df[df.age >= 18 and df.city == 'Tashkent']
print(df[(df.age <= 28) & (df.city != 'Tashkent')])
# df[df.age >= 18 && df.city == 'Tashkent']
# df.filter(age=28, city='Tashkent')
df


# so I was wrong, and the correct one seems to be version B that uses '&' sighn

   name  age       city
1  Zara   28  Samarkand

     name  age       city
0     Ali   22   Tashkent
1    Zara   28  Samarkand
2   Jasur   31    Bukhara
3  Madina   17   Tashkent
4  Otabek   45  Samarkand

### 🛠 Practice

Write **three** boolean filters on `df`:
1. People over 25 *and* not in Tashkent.
2. People in Tashkent *or* in Bukhara.
3. The youngest person (use a comparison against `df.age.min()`).

After each filter, write one sentence about *who* the filter selected and *why*.

In [63]:
# Filter 1
print(df[(df.age > 25) & (df.city != 'Tashkent')])
# here we printed those of age older than 25 and not in Tashkent
# Filter 2
print(df[(df.city == 'Tashkent') | (df.city == 'Bukhara')])
# here we printed those of Tashkent or Bukhara
# Filter 3
print(df[df.age == df.age.min()])
# here we printed the youngest person with the help of .min() function that gives the minimum within the set

     name  age       city
1    Zara   28  Samarkand
2   Jasur   31    Bukhara
4  Otabek   45  Samarkand
     name  age      city
0     Ali   22  Tashkent
2   Jasur   31   Bukhara
3  Madina   17  Tashkent
     name  age      city
3  Madina   17  Tashkent

### 3c. GroupBy — split-apply-combine

In [66]:
df.groupby('city')['age'].mean()

city
Bukhara      31.0
Samarkand    36.5
Tashkent     19.5
Name: age, dtype: float64

### ✍️ Explain — *the lecture's Quick Check #3*

What type does the cell above return? Choose one and justify in 2 sentences:
- DataFrame - this one, because here we will have data with two series, which is dataframe
- Series indexed by city
- list
- scalar

Now run `type(df.groupby('city')['age'].mean())` to verify.

In [67]:
type(df.groupby('city')['age'].mean())

# ok i was wrong. it seems as only the value of age is in interest it is considered just series. we are using city just for grouping like an index it seems

pandas.core.series.Series

In [68]:
# Run this to compare
result = df.groupby('city')['age'].mean()
print(type(result))
print(result)

<class 'pandas.core.series.Series'>
city
Bukhara      31.0
Samarkand    36.5
Tashkent     19.5
Name: age, dtype: float64

### 🛠 Practice

Use `.agg()` with a dict to compute, in **one** call:
- average `age` per city
- count of names per city
- the *youngest* person's age per city (use `'min'`)

In [76]:
# Your single-call .agg() here
df.groupby('city').agg({'age' : ['mean', 'count'], 'name' : ['min']})

            age          name
           mean count     min
city
Bukhara    31.0     1   Jasur
Samarkand  36.5     2  Otabek
Tashkent   19.5     2     Ali

### 3d. Merging

### 🤔 Predict

I have two DataFrames. Customers (5 rows) and Orders (3 rows, only some customers have ordered). I run:

```python
pd.merge(customers, orders, on='customer_id', how='left')
```

Predict:
- How many rows in the result? - 8 raws probably
- For customers without orders, what fills the order columns? if customer doesn't have ordered yet, they will be given the value 'left'
- If I changed `how='inner'`, how many rows would I get? the same raws with inner for unordered places i guess

In [77]:
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 5],
    'name': ['Ali', 'Zara', 'Jasur', 'Madina', 'Otabek']
})
orders = pd.DataFrame({
    'customer_id': [1, 1, 3],
    'amount': [50000, 75000, 30000]
})

left = pd.merge(customers, orders, on='customer_id', how='left')
inner = pd.merge(customers, orders, on='customer_id', how='inner')

print('--- LEFT join ---')
print(left)
print()
print('--- INNER join ---')
print(inner)

--- LEFT join ---
   customer_id    name   amount
0            1     Ali  50000.0
1            1     Ali  75000.0
2            2    Zara      NaN
3            3   Jasur  30000.0
4            4  Madina      NaN
5            5  Otabek      NaN

--- INNER join ---
   customer_id   name  amount
0            1    Ali   50000
1            1    Ali   75000
2            3  Jasur   30000

### ✍️ Explain

1. Why does the LEFT join have 6 rows but the INNER has only 3? when we used left it just lef NaN values and printed them too, but when we used INNER it dropped all the raws with NaN values
2. Notice that customer 1 appears twice in LEFT — explain why.as we are merging according to customer_id and Ali as two 1 as customer ID, so when we merge it with customer_id from orders, it gives the values of 1 to both ali
3. *Quick Check from the lecture:* In one sentence, what is the rule for what happens to unmatched left rows in a LEFT join? they automatically will be filled with NaN values ?

### 🛠 Practice — capstone for today

Combine everything in this section:
1. Add a `region` lookup DataFrame (Tashkent → 'Capital', Samarkand → 'South', Bukhara → 'South', etc.).
2. Merge it into your customer DataFrame.
3. GroupBy region and compute total order `amount` per region (combine with the orders DataFrame).
4. Filter to show only regions with total > 80000.
5. In a markdown cell, write 2–3 sentences explaining the business interpretation of your result.

In [92]:
# Capstone work below
regions = pd.DataFrame({
    'Tashkent' : ['Capital'],
    'Samarkand' : ['South'],
    'Bukhara' : ['South']
})

KeyError: 'Samarkand'

---
## End-of-class checkpoint quiz

Answer all 5 in markdown cells. These are the same 5 questions from the lecture page — bring written answers to the next class.

1. `loc` vs `iloc` — which is which, and when do you reach for each?
2. Why does `df[df.age >= 18 and df.city == 'T']` raise an error, and how do you fix it?
3. What does `df.groupby('city')['age'].mean()` return — DataFrame, Series, list, or scalar?
4. In a left join, what happens to rows in the *left* table that have no match in the right table?
5. A 5GB CSV crashes your laptop. What is the first move? (Two valid answers — give both.)